@host = http://localhost:3000

POST {{host}}/api/users/register
Content-Type: application/json

{
  "username": "johndoe",
  "email": "johndoe@example.com",
  "password": "secret"
}

###

POST {{host}}/api/users/login
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "secret"
}